name: Quality

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt        
      - name: Run black
        run: |
          black -l 79 *.py app tests
      - name: Run isort
        run: |
          isort -l 79 --profile black *.py app tests
      - name: Run autoflake
        run: |
          autoflake *.py app tests -r --remove-all-unused-imports --in-place --remove-unused-variables
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Autoformat code with Black" || true
          git push

